version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/hellaevents
    volumes:
      - ./:/var/www/hellaevents
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www/hellaevents
    volumes:
      - app
    ports:
      - 8080:80
volumes:
  app:
  dbdata:
