version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/hellaevents
    container_name: hella-app
    volumes:
      - ./:/var/www/hellaevents
    networks:
      - hellaevents
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www/hellaevents
    container_name: hella-web
    volumes:
      - app
    ports:
      - 8080:80
    networks:
      - hellaevents
  db:
    image: mysql:5.7.28
    container_name: hella-db
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: hellaevents_dev
    ports:
      - "3308:3306"
    networks:
      - hellaevents

networks:
  hellaevents:
    driver: bridge
